### PR TITLE
Closes #58 - Update Angular to v15

### LINKED ISSUE #58: Update to Angular 15
As we are using an outdated version of Angular, we should update to the latest version in an incremental fashion.

This issue refers to the update from Angular 14 to Angular 15.

### PR DESCRIPTION
**Pull request by CRoberto1926**
### Thanks for your PR! Please fill out the following list :)

---

- [ ] I put the ticket or multiple tickets in review
- [x] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [x] Sonarcloud link : https://sonarcloud.io/summary/new_code?id=CRoberto1926_kadai&branch=chore%2Fangular-15
- [x] No documentation update needed
- [ ] Link to PR with documentation update: \<add the link here>
- [x] No Release Notes needed
- [ ] Release Notes :

```

```

### CODE REVIEW

**Comment by ryzheboka** [comment]
Notifications don't disappear anymore. They should disappear after a few seconds 
grafik

**Comment by ryzheboka** [comment]
When selecting AccessItems in the side menu, you get stuck in the loading screen 
grafik

**Comment by CRoberto1926** [comment]
> Notifications don't disappear anymore. They should disappear after a few seconds grafik

@ryzheboka I solved this in my last commit. Could you please check it?

**Comment by CRoberto1926** [comment]
> When selecting AccessItems in the side menu, you get stuck in the loading screen grafik

This is not an issue introduced with Angular 15. You can reproduce it here https://kadai-io.azurewebsites.net/kadai/#/kadai/administration/access-items-management and even here https://taskana.azurewebsites.net/taskana/#/taskana/administration/access-items-management

It is probably better to open an issue for this bug.

**Review by ryzheboka — APPROVED** [review]

**Pull request merged**
